name: CI/CD for .NET 7.0

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal


  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      DEPLOYMENT_PATH: /home/fira/private/api

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.100

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Deploy to Server
        run: |
          scp -r publish/* ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:${{ env.DEPLOYMENT_PATH }}
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "export ASPNETCORE_ENVIRONMENT=Development"
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh fira@firar.live 'echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S bash /home/fira/private/api/restart.sh'

  